Repository pantos-io/common, pull requests merged in 2024-07, with the labels that each got.

#40 [PAN-2072] handle root configuration path
  pantos/common/blockchains/base.py
  pantos/common/configuration.py
  pantos/common/health.py
  pantos/common/restapi.py
Labels: bug, enhancement

#42 [PAN-1998] Upgrade to hexbytes 1.x
  pantos/common/blockchains/ethereum.py
  poetry.lock
  pyproject.toml
  tests/blockchains/test_ethereum.py
Labels: dependencies

#44 [PAN-2093] rawTransaction renamed to raw_transaction in Web3.py
  pantos/common/blockchains/ethereum.py
  poetry.lock
  pyproject.toml
Labels: bug
