Repository pantos-io/common, pull requests merged in 2024-05, with the labels that each got.

#5 [PAN-1785] Docstrings and type hints for configuration module
  pantos/common/configuration.py
Labels: documentation

#6 [PAN-1809] upgrade python to 3.12 and switch to poetry
  .github/actions/install-deps/action.yml
  .github/workflows/ci-cd.yaml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .pre-commit-config.yaml
  Makefile
  README.md
  pantos/common/blockchains/contracts/avalanche_pantos_forwarder.abi
  pantos/common/blockchains/contracts/avalanche_pantos_hub.abi
  pantos/common/blockchains/contracts/avalanche_pantos_token.abi
  pantos/common/blockchains/contracts/avalanche_standard_token.abi
  pantos/common/blockchains/contracts/bnb_chain_pantos_forwarder.abi
  pantos/common/blockchains/contracts/bnb_chain_pantos_hub.abi
  pantos/common/blockchains/contracts/bnb_chain_pantos_token.abi
  pantos/common/blockchains/contracts/bnb_chain_standard_token.abi
  pantos/common/blockchains/contracts/celo_pantos_forwarder.abi
  pantos/common/blockchains/contracts/celo_pantos_hub.abi
  pantos/common/blockchains/contracts/celo_pantos_token.abi
  pantos/common/blockchains/contracts/celo_standard_token.abi
  pantos/common/blockchains/contracts/cronos_pantos_forwarder.abi
  pantos/common/blockchains/contracts/cronos_pantos_hub.abi
  pantos/common/blockchains/contracts/cronos_pantos_token.abi
  pantos/common/blockchains/contracts/cronos_standard_token.abi
  pantos/common/blockchains/contracts/ethereum_pantos_forwarder.abi
  pantos/common/blockchains/contracts/ethereum_pantos_hub.abi
  pantos/common/blockchains/contracts/ethereum_standard_token.abi
  pantos/common/blockchains/contracts/fantom_pantos_forwarder.abi
  pantos/common/blockchains/contracts/fantom_pantos_hub.abi
  pantos/common/blockchains/contracts/fantom_pantos_token.abi
  pantos/common/blockchains/contracts/fantom_standard_token.abi
  pantos/common/blockchains/contracts/polygon_pantos_forwarder.abi
  pantos/common/blockchains/contracts/polygon_pantos_hub.abi
  pantos/common/blockchains/contracts/polygon_pantos_token.abi
  pantos/common/blockchains/contracts/polygon_standard_token.abi
  poetry.lock
  pyproject.toml
  requirements.txt
  setup.py
  sonar-project.properties
  tests/test_signer.py
Labels: enhancement

#9 [PAN-1875] Added CI tests badge
  README.md
Labels: documentation

#10 [PAN-1808] set wheel as default make target and update author
  Makefile
  pyproject.toml
Labels: enhancement

#13 [IGNORE] [PAN-1881] add sonar workflow
  .github/workflows/ci.yaml
  .github/workflows/sonar.yaml
Labels: donotmerge

#17 [PAN-1889] Use python-versions matrix in CI
  .github/workflows/ci.yaml
  .github/workflows/sonar.yaml
Labels: dependencies

#22 [PAN-1850] Publish to PyPI
  .github/workflows/release.yaml
  .gitignore
  Makefile
Labels: enhancement, dependencies

#21 [PAN-1898] add pantos logo
  .github/pantos-logo-full.svg
  README.md
Labels: documentation

#23 [PAN-1906] missing pypi reference
  README.md
  pyproject.toml
Labels: documentation

#29 [PAN-1912] Prepare shared namespace for package
  Makefile
  README.md
  pantos/__init__.py
  pyproject.toml
Labels: enhancement
